name: Deploy AI

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Logout from Docker Hub (if exists)
        run: docker logout || true

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Add environment variables to .env
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> app/.env
          echo "SAVILY_API_KEY=${{ secrets.SAVILY_API_KEY }}" >> app/.env
          echo "HF_TOKEN=${{ secrets.HF_TOKEN }}" >> app/.env

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ai:latest .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ai:latest

      - name: Deploy on AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/ai:latest
            docker stop ai || true
            docker rm ai || true
            docker images --filter=reference="${{ secrets.DOCKER_USERNAME }}/ai" -q | xargs docker rmi -f || true
            docker run -d --name ai -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/ai:latest
